language: python
python:
- 3.6

before_install:
- openssl aes-256-cbc -K $encrypted_d60fb473bc42_key -iv $encrypted_d60fb473bc42_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar

install:
- pip install -r requirements.txt

script:
- python manage.py test

before_script:
- cd nanum