language: python
python:
- 3.6
install:
- pip install -r requirements.txt
before_script:
- cd nanum
script:
- python manage.py test
before_install:
- openssl aes-256-cbc -K $encrypted_d60fb473bc42_key -iv $encrypted_d60fb473bc42_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
